---
title: "Data Dictionary"
editor: visual
---

| Variable   | Class     | Description                                                                                                                              |
|------------|-----------|------------------------------------------------------------------------------------------------------------------------------------------|
| year       | integer   | Year that wage information was recorded                                                                                                  |
| age        | integer   | Age of worker                                                                                                                            |
| maritl     | character | A factor with levels `1. Never Married` `2. Married` `3. Widowed` `4. Divorced` and `5. Separated` indicating marital status             |
| race       | character | A factor with levels `1. White` `2. Black` `3. Asian` and `4. Other` indicating race                                                     |
| education  | character | A factor with levels `1. < HS Grad` `2. HS Grad` `3. Some College` `4. College Grad` and `5. Advanced Degree` indicating education level |
| region     | character | Region of the country (mid-atlantic only)                                                                                                |
| jobclass   | character | A factor with levels `1. Industrial` and `2. Information` indicating type of job                                                         |
| health     | character | A factor with levels `1. <=Good` and `2. >=Very Good` indicating health level of worker                                                  |
| health_ins | character | A factor with levels `1. Yes` and `2. No` indicating whether worker has health insurance                                                 |
| logwage    | float     | Log of workers wage                                                                                                                      |
| wage       | float     | Workers raw wage                                                                                                                         |

: Table: Data Dictionary {.striped .hover}

```{r, echo=FALSE, warning=FALSE}
library(pointblank)
library(ISLR2)
Wage = Wage
my_informant <- create_informant(Wage,
                                 label = "Wage data was manually assembled by Steve Miller")
my_informant
```
